# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dancelife-dev-nodejs

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Default env to pass test run during deployment
env:
  TZ: UTC
  PORT: 3333
  HOST: localhost
  LOG_LEVEL: info
  APP_KEY: testtesttesttest
  NODE_ENV: development
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_USER: root
  DB_PASSWORD: root
  DB_DATABASE: app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # - name: Install dependencies in build folder
      #   run: |
      #     cd build && npm install && cd ..
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8E12B4D550E84C728AC32258633B5473 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D5DCB0DF7C24D60836DF4430D37A7F4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D232A08FD60A4B03925E16B1BFE5EB03 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dancelife-dev-nodejs'
          slot-name: 'Production'
          package: './build'
          